# Generated by Django 3.2.6 on 2021-08-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210811_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
