# Generated by Django 3.2.6 on 2021-08-13 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
