# Generated by Django 3.2.6 on 2021-08-20 12:08

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_like_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 8, 20, 12, 8, 3, 458749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
