# Generated by Django 3.2.6 on 2021-08-20 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210820_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
